In [1]:
2+5

7

# print("heeloo")

In [3]:
"heelllo"

'heelllo'

In [4]:
print(3+2.5)

5.5


In [7]:
print(2*"aksjh")

aksjhaksjh


# dictionary
{key:value}
easy to access data

In [2]:
dict1={'a':5,'b':6}

In [3]:
dict1['a']

5

In [4]:
dict1.keys()

dict_keys(['a', 'b'])

In [5]:
dict1.values()

dict_values([5, 6])

In [6]:
dict2={'a':5,'b':6,'b':7}

In [7]:
dict2['b']

7

# sets {}
duplicate elements are removed(unique )


In [8]:
set1={1,2,3,4,5,5,3,2,1}

In [9]:
set1

{1, 2, 3, 4, 5}

In [10]:
set1.add(2)

In [12]:
set1.add(8)

In [13]:
set1

{1, 2, 3, 4, 5, 8}

# functions

def add(a,b)

In [15]:
def add(a,b):
    print(a+b)
    
    

In [16]:
add(5,6)

11


In [17]:
add('v','t')

vt


# numpy 
used for scientific calc 


In [3]:
import numpy as np

In [21]:
a=np.array([1,2,3,4,5,56])

In [22]:
a

array([ 1,  2,  3,  4,  5, 56])

In [23]:
a.ndim

1

In [26]:
a=np.array([[1,2,3,4],[2,3,4,5]])

In [27]:
a.ndim

2

In [29]:
a.shape#(row,column)

(2, 4)

In [30]:
a=np.array([[1,2,3,4],[2,3,4,5]],dtype=float)

In [31]:
a


array([[1., 2., 3., 4.],
       [2., 3., 4., 5.]])

In [50]:
a=np.array([[[1,2,3,4],[2,3,4,5],[2,3,4,5]]])#3dimensional array

In [1]:
a.ndim

NameError: name 'a' is not defined

In [45]:
a.shape

(1, 3, 4)

In [46]:
a[0]

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [2, 3, 4, 5]])

In [48]:
a[0][0]

array([1, 2, 3, 4])

In [49]:
a[0][0][0]

1

In [53]:
a.all()#all element non zero array then true

True

In [54]:
a.any()# any element non zero it will give true

True

In [55]:
a=np.array([1,2,3,4,5,6,7,8])

In [56]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [57]:
a.reshape((2,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [58]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [59]:
a.reshape((2,4)).shape

(2, 4)

In [60]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [62]:
np.eye(5) #for identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [63]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [65]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [66]:
np.zeros((3,4)).any()

False

In [67]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [68]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [69]:
a+10

array([11, 12, 13, 14, 15, 16, 17, 18])

In [71]:
np.dot(a,a)#dot product

204

In [73]:
c=np.array([[1,2],[5,9]])

In [76]:
c.ndim

2

In [77]:
d=np.array([[6,10],[8,11]])

In [78]:
np.dot(c,d)

array([[ 22,  32],
       [102, 149]])

In [80]:
e=10*np.dot(c,d)

In [81]:
e

array([[ 220,  320],
       [1020, 1490]])

In [82]:
dir(e) #to display functions

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [84]:
help(np.full) #to check arguments

Help on function full in module numpy:

full(shape, fill_value, dtype=None, order='C')
    Return a new array of given shape and type, filled with `fill_value`.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    fill_value : scalar
        Fill value.
    dtype : data-type, optional
        The desired data-type for the array  The default, `None`, means
         `np.array(fill_value).dtype`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    
    Returns
    -------
    out : ndarray
        Array of `fill_value` with the given shape, dtype, and order.
    
    See Also
    --------
    full_like : Return a new array with shape of input filled with value.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    zeros : Return a new array setting values 

In [85]:
np.full((2,4),6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6]])

In [5]:
np.loadtxt("C:/Users/khush/desktop/textfile.txt",delimiter=',')

array([[1., 2., 3., 4.],
       [4., 5., 6., 7.]])

### pandassss
data is in tabular form not in array

In [7]:
import pandas as pd

In [12]:
pd.Series([1,2,3,4,5]) #for single column we use series

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [9]:
pd.Series([1,2,3,4,5],index=[1,2,3,4,5])

1    1
2    2
3    3
4    4
5    5
dtype: int64

In [10]:
pd.Series([1,2,3,4,5],index=[1,2,3,4,5],dtype=float)

1    1.0
2    2.0
3    3.0
4    4.0
5    5.0
dtype: float64

In [13]:
#for more than one column
#data frame is used

In [28]:
df=pd.DataFrame({'a':[1,4,7],'b':[2,5,8],'c':[3,6,9]},index=[1,2,3])   #using dictionary

In [29]:
df

a  b  c
1  1  2  3
2  4  5  6
3  7  8  9

In [26]:
#using list
df1=pd.DataFrame([[1,4,7],[2,5,8],[3,6,9]],index=[1,2,3],columns=['a','b','c'])

In [27]:
df1

a  b  c
1  1  4  7
2  2  5  8
3  3  6  9

In [31]:
df1.head(2) #to access particular num of rows from starting

a  b  c
1  1  4  7
2  2  5  8

In [33]:
df1.tail(1) #from bottom

a  b  c
3  3  6  9

In [36]:

df1['a']  #accessing columns

1    1
2    2
3    3
Name: a, dtype: int64

In [38]:
df2=pd.DataFrame({'a':[1,'',7],'b':[2,5,8],'c':[3,'',9]},index=[1,2,3])

In [39]:
df2

a  b  c
1  1  2  3
2     5   
3  7  8  9

In [40]:
df2.replace('',3)

a  b  c
1  1  2  3
2  3  5  3
3  7  8  9

In [41]:
df2['a'][2]

''

In [45]:
df2['a'][2]=9

C:\Users\khush\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [81]:
df2.to_csv("C:/Users/khush/desktop/python1.csv") #saving file in csv format with index

In [82]:
df2.to_csv("C:/Users/khush/desktop/python2.csv",index=False)#saving file in csv format without index

In [77]:
df2=pd.read_csv("C:/Users/khush/desktop/python1.csv")

In [78]:
df2

Unnamed: 0  a  b    c
0           1  1  2  3.0
1           2  9  5  NaN
2           3  7  8  9.0

In [79]:
df2=pd.read_csv("C:/Users/khush/desktop/python2.csv")

In [80]:
df2

a  b    c
0  1  2  3.0
1  9  5  NaN
2  7  8  9.0

In [84]:
df2.drop('a',axis=1)  #axis=1 to check in column and axis=0(default ) to check row

b    c
0  2  3.0
1  5  NaN
2  8  9.0

In [ ]:
c=input("enter integer number")

In [107]:
d=0
a=[]
b=[]
while d<=int(c):
    
    if(d%2==0):
        #df1=pd.DataFrame({"even":[d]},copy=True)
        a.append(d)
        d=d+1
    else:
        #df1=pd.DataFrame({"odd":[d]},copy=True)
        b.append(d)
        d=d+1
l=pd.DataFrame({"even":a,"odd":b})        

In [89]:
i=0
for i in range(6):  #for loop
    print(i)

0
1
2
3
4
5


In [108]:
l

even  odd
0      0    1
1      2    3
2      4    5
3      6    7
4      8    9
5     10   11
6     12   13
7     14   15
8     16   17
9     18   19
10    20   21
11    22   23
12    24   25
13    26   27
14    28   29
15    30   31
16    32   33
17    34   35
18    36   37
19    38   39
20    40   41
21    42   43
22    44   45
23    46   47
24    48   49
25    50   51
26    52   53
27    54   55
28    56   57
29    58   59
30    60   61
31    62   63
32    64   65
33    66   67
34    68   69
35    70   71
36    72   73
37    74   75
38    76   77
39    78   79
40    80   81
41    82   83
42    84   85
43    86   87
44    88   89
45    90   91
46    92   93
47    94   95
48    96   97
49    98   99
50   100  101

In [109]:
l.to_csv("C:/Users/khush/desktop/oddeven.csv",index=False)

In [110]:
pd.read_csv("C:/Users/khush/desktop/oddeven.csv")

even  odd
0      0    1
1      2    3
2      4    5
3      6    7
4      8    9
5     10   11
6     12   13
7     14   15
8     16   17
9     18   19
10    20   21
11    22   23
12    24   25
13    26   27
14    28   29
15    30   31
16    32   33
17    34   35
18    36   37
19    38   39
20    40   41
21    42   43
22    44   45
23    46   47
24    48   49
25    50   51
26    52   53
27    54   55
28    56   57
29    58   59
30    60   61
31    62   63
32    64   65
33    66   67
34    68   69
35    70   71
36    72   73
37    74   75
38    76   77
39    78   79
40    80   81
41    82   83
42    84   85
43    86   87
44    88   89
45    90   91
46    92   93
47    94   95
48    96   97
49    98   99
50   100  101

### more pandas funct

In [5]:
import pandas as pd

In [6]:
df=pd.DataFrame({'a':[1,2,3],'b':[4,3,2],'c':[7,6,8]},index=[1,2,3])

In [7]:
df

a  b  c
1  1  4  7
2  2  3  6
3  3  2  8

In [9]:
df.loc[:,'a'] # access in new way 

1    1
2    2
3    3
Name: a, dtype: int64

In [10]:
df.loc[:1,'a']

1    1
Name: a, dtype: int64

In [11]:
df.loc[:1,'a']=9

In [12]:
df

a  b  c
1  9  4  7
2  2  3  6
3  3  2  8

In [13]:
df.loc[:,:'c']

a  b  c
1  9  4  7
2  2  3  6
3  3  2  8

In [15]:
df.loc[:,'b':'c'] #accessing any row with column

b  c
1  4  7
2  3  6
3  2  8

In [1]:
df.ix[:,1] #access data through index

NameError: name 'df' is not defined

In [19]:
df.append({'a':7,'b':5,'c':3},ignore_index=True) ##appending data frame

a  b  c
0  9  4  7
1  2  3  6
2  3  2  8
3  7  5  3

In [20]:
type(df)

pandas.core.frame.DataFrame

In [22]:
df.as_matrix() # converting in matrix without numpy

C:\Users\khush\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([[9, 4, 7],
       [2, 3, 6],
       [3, 2, 8]], dtype=int64)

In [24]:
type(df.as_matrix())

C:\Users\khush\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


numpy.ndarray

In [26]:
pd.np.array([1,2,3,4,5])
#numpy inside panda

array([1, 2, 3, 4, 5])

In [28]:
df.isna() #checking empty spaces

a      b      c
1  False  False  False
2  False  False  False
3  False  False  False

In [1]:
import cv2

im=cv2.imread("C:/Users/khush/Desktop/F.jpg")

im1=(cv2.resize(im,(500,600)))

cv2.imshow("show",im1)

